apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
# these are deployment labels
  labels:
    purpose: ingress
    project: roboshop
    app: app1
spec:
  replicas: 2
# these are the labels replicaset use to create pod replicas, this should match the pod labels
  selector:
    matchLabels:
      purpose: ingress
      project: roboshop
      app: app1
# this is pod definition
  template:
    metadata:
      labels:
        purpose: ingress
        project: roboshop
        app: app1
    spec:
      containers:
      - name: app1
        image: praneeth2701/app1:v1